(KMS/DRM) add support for custom modes (from hdmi timings
libretro/RetroArch pull request #11590
Opened 2020-11-18 10:59 UTC by Cpasjuste

## Description

This changes add support for custom drm display modes in the kms/drm driver. It allow using custom hdmi timings by using this configuration :

`video_fullscreen = "true"`
`crt_switch_timings = "640 1 16 96 48 480 0 10 2 33 0 0 0 60 0 25175000 1"`

The main usage is when using kms/drm on a CRT TV on the RPI4 (or any kms/drm enabled platform with a CRT TV). 
The RPI4 does not allow changing timings on the fly because of the drm/kms video driver (https://github.com/raspberrypi/firmware/issues/1357), we have to use the drm layer for this. Since a CRT TV "drm connector" will only report the the main mode (hdmi_timings set in config.txt), it was not possible to use multiples resolutions on a RPI4 + CRT TV. 

After some investigations, i discovered that it's possible to use an arbitrary mode with "drmModeSetCrtc", allowing just that. Note that a function exist to add custom modes (drmModeAttachMode), but from my testing it's not working either on linux or rpi, and this is deprecated.

The choice of using "hdmi_timings" (and not  drmModeModeInfo) is motivated by the fact that people are using this since a while on the PI and setting/configuration for different crt tv/cores are widely available. "hdmi_timings" will be converted to drmModeModeInfo on the fly, but the hskew/vscan settings may need investigations.

A web search will show that a lot of people are waiting for this (rpi4 + crt tv + resolution switching).

2020-11-18 14:40 UTC, Cpasjuste commented on gfx/drivers_context/drm_ctx.c
> +      modeInfo->vscan = 0; // TODO: ??
I'm not sure if this value should be set/used, it doesn't seems to be the case in the "[rpi drm driver mode conversion](https://github.com/raspberrypi/linux/blob/rpi-5.4.y/drivers/gpu/drm/drm_modes.c#L587)"

2020-11-18 15:56 UTC, rtomasa commented
Super!
Sorry, I'm very interested and I have many questions on this.
Will be these two new props binded to work with the crt_switchres functionality in any way?
Actually just having the possibility of using the same manually per core will be a huge improvement over the fixed resolution that we now have.
Also, do you think that Pi4 open pixel clock could be able to manage interlaced modes by using this method?

2020-11-18 16:26 UTC, Cpasjuste commented
> Super!
> Sorry, I'm very interested and I have many questions on this.
> Will be these two new props binded to work with the crt_switchres functionality in any way?
> Actually just having the possibility of using the same manually per core will be a huge improvement over the fixed resolution that we now have.
> Also, do you think that Pi4 open pixel clock could be able to manage interlaced modes by using this method?

Hi,

I didn't look at how crt_switch_resolution* works, but I guess it use vcgencmd hdmi_timings command to switch mode, which is not possible on rpi. I'll take a closer look but for now they shouldn't be used in conjunction (you can achieve the same with this new props + custom ratio + custom viewport if needed).

Else, this method works like the hdmi_timings line put in config.txt, so it won't have any advantage over it!

2020-11-18 17:06 UTC, rtomasa commented
Well, the advantage is that this works 😂
Thanks for your work and for the details.
________________________________
De: Cpasjuste <notifications@github.com>
Enviado: miércoles, 18 de noviembre de 2020 17:26
Para: libretro/RetroArch <RetroArch@noreply.github.com>
Cc: Rubén Tomás <ruben.tomas@outlook.com>; Manual <manual@noreply.github.com>
Asunto: Re: [libretro/RetroArch] (KMS/DRM) add support for custom modes (#11590)


Super!
Sorry, I'm very interested and I have many questions on this.
Will be these two new props binded to work with the crt_switchres functionality in any way?
Actually just having the possibility of using the same manually per core will be a huge improvement over the fixed resolution that we now have.
Also, do you think that Pi4 open pixel clock could be able to manage interlaced modes by using this method?

Hi,

I didn't look at how crt_switch_resolution* works, but I guess it use vcgencmd hdmi_timings command to switch mode, which is not possible on rpi. I'll take a closer look but for now they shouldn't be used in conjunction (you can achieve the same with this new props + custom ratio + custom viewport if needed).

Else, this method works like the hdmi_timings line put in config.txt, so it won't have any advantage over it!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://github.com/libretro/RetroArch/pull/11590#issuecomment-729793452>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ADXDABZEJFTJV727LMFANILSQPYVFANCNFSM4TZZ6THA>.

2020-11-18 22:26 UTC, rtomasa commented
Sorry for bothering you again but, since this is intended for KMS, I'm wondering how did you managed to test the same? I mean, for using vga666 or RGB-Pi you are required to use their corresponding dtbo, but when using it on Pi4+Buster, there is not image because of the DRI, so I found out that using them in conjunction the Adafruit dri dtbo, the devices work BUT retroarch then is not able to get any video device driver information so is not able to run. Any advise on this?

2020-11-19 04:42 UTC, twinaphex requested changes

2020-11-19 04:42 UTC, twinaphex commented on gfx/drivers_context/drm_ctx.c
> +      // check for custom crt hdmi timings
Use a C-style comment here instead of C++.

2020-11-19 09:31 UTC, Cpasjuste commented
> Sorry for bothering you again but, since this is intended for KMS, I'm wondering how did you managed to test the same? I mean, for using vga666 or RGB-Pi you are required to use their corresponding dtbo, but when using it on Pi4+Buster, there is not image because of the DRI, so I found out that using them in conjunction with the Adafruit vc4-kms-kippah-7inch dtbo, the devices work BUT retroarch then is not able to get any video device driver information so is not able to run. Any advise on this?

Hi,

I'm using the Pi2SCART with the vga666 dtb on my pi4 and, and having no problem on buster. I'm not sure if the retroarch version which comes with buster have the "non X" kms/drm driver thought as i'm working with it compiled from sources. Do you, at least, see the consoles logs before it completely boot ? 
Here is the config i'm using: https://pastebin.com/bGFzh4PF

2020-11-19 10:05 UTC, rtomasa commented
> > Sorry for bothering you again but, since this is intended for KMS, I'm wondering how did you managed to test the same? I mean, for using vga666 or RGB-Pi you are required to use their corresponding dtbo, but when using it on Pi4+Buster, there is not image because of the DRI, so I found out that using them in conjunction with the Adafruit vc4-kms-kippah-7inch dtbo, the devices work BUT retroarch then is not able to get any video device driver information so is not able to run. Any advise on this?
> 
> Hi,
> 
> I'm using the Pi2SCART with the vga666 dtb on my pi4 and, and having no problem on buster. I'm not sure if the retroarch version which comes with buster have the "non X" kms/drm driver thought as i'm working with it compiled from sources. Do you, at least, see the consoles logs before it completely boot ?
> Here is the config i'm using: https://pastebin.com/bGFzh4PF

Mmmm I had almost this same configuration in the config.txt. Actually I've tested with all legacy, FKMS and KMS drivers, and using the latter two FKMS and KMS I only get black screen on boot if not using the Adafruit one too. I was testing a couple of months ago so maybe there is some new patch in the kernel or something that fixed that issue. Definelty, it is something that I'll be testing today.

BTW when I was doing all the testing, I compiled retroarch from source (1.8.5) in my Pi4 using the following flags:

`CFLAGS='-mfpu=neon -mtune=cortex-a72 -march=armv8-a' ./configure --enable-opengles --enable-opengles3 --enable-kms --disable-videocore --enable-plain_drm --disable-opengl1 --enable-neon --enable-floathard --enable-alsa --enable-udev --disable-x11 --disable-pulse --disable-oss `

2020-11-19 12:45 UTC, merged

2020-12-11 19:55 UTC, myzar commented
Does this really change resolution or it's only pretending like the broken fbset which tries to fix ? I've compiled master and i was eager to test because i'm in the many who miss that ability having a crt cab. 
I've tried  adding the common pixel perfect res 

crt_switch_timings =  "1920 1 152 247 280 240 1 3 7 12 0 0 0 60 0 40860000 1" 

from the logs i see 

[INFO] [DRM]: Connector 0 assigned to monitor index: #1.
[INFO] [DRM]: Mode 0: (FIXED_MODE) 320 x 240, 60 Hz
[INFO] [GL]: Found GL context: kms
[INFO] [GL]: Detecting screen resolution 1920x240.
[INFO] [DRM]: custom mode requested: CRT_1920x240_60
[INFO] [EGL] Falling back to eglGetDisplay
[INFO] [EGL]: EGL version: 1.4
[INFO] [EGL]: Current context: 0xaa81ffa8.
[INFO] [KMS]: New FB: 1920x240 (stride: 7680).
[INFO] [GL]: Vendor: Broadcom, Renderer: V3D 4.2.
[INFO] [GL]: Version: OpenGL ES 3.1 Mesa 21.0.0-devel (git-872c4bcd27).
[INFO] [GL]: Using resolution 1920x240
[INFO] [GL]: Default shader backend found: glsl.

But everything is super giant like if you zoomed 320x240 to 1920x240 without any scaling , i don't think that is changing the res for real because i can put bogus timing values where my monitor wouldn't sync or display anything if it did.

I'm using the vga666 overlay and the vc4-fkms-v3d overlay

2020-12-11 20:11 UTC, Cpasjuste commented
Hi,

You're right, the "switchres" (resolution change) is not really happening, and it's an error on my side.
When I was working on this retroarch PR, I was also working on a (dpi-dac) kernel module who does really allow switching resolution. So this PR does work, but only if you are using my custom dtb and kernel module.
I'm really sorry about this, this sort of error is very common I guess, when you think all is working fine, but only because you have something else around you didn't notice.

So, this PR can be useful, only if you use my custom dtb and module, which you can found here: http://mydedibox.fr/rpi4-custom-modes-on-a-crt-tv-the-holy-grail/

Please, let me know which distribution (and kernel if possible) you use so I can provide you with the necessary files.

Thanks for taking the time to report.

2020-12-11 21:53 UTC, myzar commented
Hi,

great work with the rpi2scart i totally understand your pain and the need to find a solution which you did, unfortunately it's not so easy , i can compile the module fine but without your vc4-vga666 it doesn't work , that dbto is specific to rpi2scart, i use another board jammapi which uses its own custom vga666 dbto ,we'd need a merge i guess this is the one for my board https://github.com/vince87/JammaPi/blob/master/vga666.dtbo

2020-12-11 21:58 UTC, Cpasjuste commented
> Hi,
> 
> great work with the rpi2scart i totally understand your pain and the need to find a solution which you did, unfortunately it's not so easy , i can compile the module fine but without your vc4-vga666 it doesn't work , that dbto is specific to rpi2scart, i use another board jammapi which uses its own custom vga666 dbto ,we'd need a merge i guess this is the one for my board https://github.com/vince87/JammaPi/blob/master/vga666.dtbo

In fact it works for any vga666 compatible hardware, which rgb-pi (and probably jamma-pi) doesn't comply with.
The good thing is I just received a rgb-pi scart cable today from the rgb-pi team (which is believe use the same overlay as your jamma-pi?), so there is hope for your 👍

2020-12-13 11:04 UTC, krahsdevil commented
> > Hi,
> > great work with the rpi2scart i totally understand your pain and the need to find a solution which you did, unfortunately it's not so easy , i can compile the module fine but without your vc4-vga666 it doesn't work , that dbto is specific to rpi2scart, i use another board jammapi which uses its own custom vga666 dbto ,we'd need a merge i guess this is the one for my board https://github.com/vince87/JammaPi/blob/master/vga666.dtbo
> 
> In fact it works with any vga666 compatible hardware, which rgb-pi (and probably jamma-pi) doesn't comply with.
> The good thing is I just received a rgb-pi scart cable today from the rgb-pi team (which, i believe, use the same overlay as your jamma-pi?), so there is hope for your 👍

Hi.
I was testing your dpi bridge with vga666 mode5 devices (PI2SCART) and also with with mode6 ones (RGB-Pi/PiCRT).
To get it working with this last mode (6), I compiled your bridge changing MEDIA_BUS_FMT_RGB666_1X18 by MEDIA_BUS_FMT_RGB666_1X24_CPADHI which is used in vc4_dpi.c to change output format to DPI_FORMAT_18BIT_666_RGB_2.
Maybe some kind of dynamic selection on the same would be appreciated instead of having two different bridges for each mode...

Additionaly is necesary to modify vc4-vga666.dtbo to alternate between mode5 and mode 6 pinout. 
This **_vc4-vga666-overlay.dts_** approach worked for me (**dtoverlay=vc4-vga666** for mode5 and **dtoverlay=vc4-vga666,mode6** for mode6 in boot.txt):
```

/dts-v1/;
/plugin/;

/ {
	compatible = "brcm,bcm2835", "brcm,bcm2708", "brcm,bcm2709";

	fragment@0 {
		target-path = "/";
		__overlay__ {
			bridge: bridge {
				compatible = "raspberrypi,dpidac";
				#address-cells = <1>;
				#size-cells = <0>;

				display-timings {
					native-mode = <&t_240p60>;

					t_240p60: t_240p60 {
						clock-frequency = <6400000>;
						hactive = <320>;
						hfront-porch = <17>;
						hsync-len = <30>;
						hsync-active = <0>;
						hback-porch = <34>;
						vactive = <240>;
						vfront-porch = <1>;
						vsync-len = <3>;
						vsync-active = <0>;
						vback-porch = <22>;
					};
					
					t_480i60: t_480i60 {
						clock-frequency = <12800000>;
						interlaced;
						hactive = <640>;
						hfront-porch = <30>;
						hsync-len = <60>;
						hsync-active = <0>;
						hback-porch = <72>;
						vactive = <480>;
						vfront-porch = <22>;
						vsync-len = <5>;
						vsync-active = <0>;
						vback-porch = <24>;
					};
					
					t_vga: t_vga {
						clock-frequency = <25180000>;
						hactive = <640>;
						hfront-porch = <16>;
						hsync-len = <96>;
						hsync-active = <0>;
						hback-porch = <48>;
						vactive = <480>;
						vfront-porch = <10>;
						vsync-len = <2>;
						vsync-active = <0>;
						vback-porch = <33>;
					};
				};

				ports {
					#address-cells = <1>;
					#size-cells = <0>;

					port@0 {
						reg = <0>;

						vga_bridge_in: endpoint {
							remote-endpoint = <&dpi_out>;
						};
					};

					port@1 {
						reg = <1>;

						vga_bridge_out: endpoint {
							remote-endpoint = <&vga_con_in>;
						};
					};
				};
			};

			vga {
				compatible = "vga-connector";

				port {
					vga_con_in: endpoint {
						remote-endpoint = <&vga_bridge_out>;
					};
				};
			};
		};
	};
	fragment@1 {
		target = <&dpi>;
		__overlay__  {
			status = "okay";
			port {
				dpi_out: endpoint@0 {
					remote-endpoint = <&vga_bridge_in>;
				};
			};
		};
	};
	fragment@2 {
		target = <&dpi>;
		__overlay__  {
			status = "okay";
			pinctrl-names = "default";
			pinctrl-0 = <&vga666_pins>;
		};
	};
	fragment@3 {
		target = <&gpio>;
		__overlay__ {
			vga666_pins: vga666_pins {
				brcm,pins = <2 3 4 5 6 7 8 9 10 11 12
					     13 14 15 16 17 18 19 20 21>;
				brcm,function = <6>;
				brcm,pull = <0>;
			};
		};
	};
	fragment@4 {
		target = <&dpi>;
		__dormant__  {
			status = "okay";
			pinctrl-names = "default";
			pinctrl-0 = <&vga666_mode6_pins>;
		};
	};
	fragment@5 {
		target = <&gpio>;
		__dormant__ {
			vga666_mode6_pins: vga666_mode6_pins {
				brcm,pins = <2 3 4 5 6 7 8 9 12 13 14
						 15 16 17 20 21 22 23 24 25>;
				brcm,function = <6>;
				brcm,pull = <0>;
			};
		};
	};
	__overrides__ {
		mode5 = <0>,"+0+1+2+3-4-5";
		mode6 = <0>,"+0+1-2-3+4+5";
	};	
};
```
Hope it can help...

2020-12-13 11:25 UTC, Cpasjuste commented
> > > Hi,
> > > great work with the rpi2scart i totally understand your pain and the need to find a solution which you did, unfortunately it's not so easy , i can compile the module fine but without your vc4-vga666 it doesn't work , that dbto is specific to rpi2scart, i use another board jammapi which uses its own custom vga666 dbto ,we'd need a merge i guess this is the one for my board https://github.com/vince87/JammaPi/blob/master/vga666.dtbo
> > 
> > 
> > In fact it works with any vga666 compatible hardware, which rgb-pi (and probably jamma-pi) doesn't comply with.
> > The good thing is I just received a rgb-pi scart cable today from the rgb-pi team (which, i believe, use the same overlay as your jamma-pi?), so there is hope for your 👍
> 
> Hi.
> I was testing your dpi bridge with vga666 mode5 devices (PI2SCART) and also with with mode6 ones (RGB-Pi/PiCRT).
> To get it working with this last mode (6), I compiled your bridge changing MEDIA_BUS_FMT_RGB666_1X18 by **MEDIA_BUS_FMT_RGB666_1X24_CPADHI** which is used in vc4_dpi.c to change output format to **DPI_FORMAT_18BIT_666_RGB_2**.
> Maybe some kind of dynamic selection on the same would be appreciated instead of having two different bridges for each mode...
> 
> Additionaly is necesary to modify vc4-vga666.dtbo to alternate between mode5 and mode 6 pinout.
> This **_vc4-vga666-overlay.dts_** approach worked for me (**dtoverlay=vc4-vga666** for mode5 and **dtoverlay=vc4-vga666,mode6** for mode6 in boot.txt):
> 
> ```
> 
> /dts-v1/;
> /plugin/;
> 
> / {
> 	compatible = "brcm,bcm2835", "brcm,bcm2708", "brcm,bcm2709";
> 
> 	fragment@0 {
> 		target-path = "/";
> 		__overlay__ {
> 			bridge: bridge {
> 				compatible = "raspberrypi,dpidac";
> 				#address-cells = <1>;
> 				#size-cells = <0>;
> 
> 				display-timings {
> 					native-mode = <&t_240p60>;
> 
> 					t_240p60: t_240p60 {
> 						clock-frequency = <6400000>;
> 						hactive = <320>;
> 						hfront-porch = <17>;
> 						hsync-len = <30>;
> 						hsync-active = <0>;
> 						hback-porch = <34>;
> 						vactive = <240>;
> 						vfront-porch = <1>;
> 						vsync-len = <3>;
> 						vsync-active = <0>;
> 						vback-porch = <22>;
> 					};
> 					
> 					t_480i60: t_480i60 {
> 						clock-frequency = <12800000>;
> 						interlaced;
> 						hactive = <640>;
> 						hfront-porch = <30>;
> 						hsync-len = <60>;
> 						hsync-active = <0>;
> 						hback-porch = <72>;
> 						vactive = <480>;
> 						vfront-porch = <22>;
> 						vsync-len = <5>;
> 						vsync-active = <0>;
> 						vback-porch = <24>;
> 					};
> 					
> 					t_vga: t_vga {
> 						clock-frequency = <25180000>;
> 						hactive = <640>;
> 						hfront-porch = <16>;
> 						hsync-len = <96>;
> 						hsync-active = <0>;
> 						hback-porch = <48>;
> 						vactive = <480>;
> 						vfront-porch = <10>;
> 						vsync-len = <2>;
> 						vsync-active = <0>;
> 						vback-porch = <33>;
> 					};
> 				};
> 
> 				ports {
> 					#address-cells = <1>;
> 					#size-cells = <0>;
> 
> 					port@0 {
> 						reg = <0>;
> 
> 						vga_bridge_in: endpoint {
> 							remote-endpoint = <&dpi_out>;
> 						};
> 					};
> 
> 					port@1 {
> 						reg = <1>;
> 
> 						vga_bridge_out: endpoint {
> 							remote-endpoint = <&vga_con_in>;
> 						};
> 					};
> 				};
> 			};
> 
> 			vga {
> 				compatible = "vga-connector";
> 
> 				port {
> 					vga_con_in: endpoint {
> 						remote-endpoint = <&vga_bridge_out>;
> 					};
> 				};
> 			};
> 		};
> 	};
> 	fragment@1 {
> 		target = <&dpi>;
> 		__overlay__  {
> 			status = "okay";
> 			port {
> 				dpi_out: endpoint@0 {
> 					remote-endpoint = <&vga_bridge_in>;
> 				};
> 			};
> 		};
> 	};
> 	fragment@2 {
> 		target = <&dpi>;
> 		__overlay__  {
> 			status = "okay";
> 			pinctrl-names = "default";
> 			pinctrl-0 = <&vga666_pins>;
> 		};
> 	};
> 	fragment@3 {
> 		target = <&gpio>;
> 		__overlay__ {
> 			vga666_pins: vga666_pins {
> 				brcm,pins = <2 3 4 5 6 7 8 9 10 11 12
> 					     13 14 15 16 17 18 19 20 21>;
> 				brcm,function = <6>;
> 				brcm,pull = <0>;
> 			};
> 		};
> 	};
> 	fragment@4 {
> 		target = <&dpi>;
> 		__dormant__  {
> 			status = "okay";
> 			pinctrl-names = "default";
> 			pinctrl-0 = <&vga666_mode6_pins>;
> 		};
> 	};
> 	fragment@5 {
> 		target = <&gpio>;
> 		__dormant__ {
> 			vga666_mode6_pins: vga666_mode6_pins {
> 				brcm,pins = <2 3 4 5 6 7 8 9 12 13 14
> 						 15 16 17 20 21 22 23 24 25>;
> 				brcm,function = <6>;
> 				brcm,pull = <0>;
> 			};
> 		};
> 	};
> 	__overrides__ {
> 		mode5 = <0>,"+0+1+2+3-4-5";
> 		mode6 = <0>,"+0+1-2-3+4+5";
> 	};	
> };
> ```
> 
> Hope it can help...

Hi,

Yes thanks, il will save me a lot of debug time. I'll implement this asap.

Thanks again,
David.

2020-12-13 14:30 UTC, myzar commented
Very good with the suggested krahsdevil changes now it works with the jammapi too , great work !!