add source comments to input_drivers.h
libretro/RetroArch pull request #12609
Opened 2021-07-03 20:38 UTC by markwkidd

This my latest work to add documentation for the input drivers.

I have started using a minimal Doxygen-compliant style for the function prototype comments since a lot of the existing comments were close to that style already.

I'll follow up with a few questions I have about documenting some of these function.

2021-07-04 15:06 UTC, RobLoach commented on input/input_driver.h
> +    * TODO
All of these TODO notes don't really add any value.

2021-07-04 15:09 UTC, markwkidd commented
Yes I have a few questions to clear up, but I didn't finish writing them up
yesterday. I should mark this as a draft!


On Sun, Jul 4, 2021, 11:06 AM Rob Loach ***@***.***> wrote:

> *@RobLoach* commented on this pull request.
> ------------------------------
>
> In input/input_driver.h
> <https://github.com/libretro/RetroArch/pull/12609#discussion_r663517240>:
>
> >     enum retro_key key;
>
> +   /**
> +    * TODO
>
> All of these TODO notes don't really add any value.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/libretro/RetroArch/pull/12609#pullrequestreview-698684289>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEVGC5WXX7GU5EM2LSVBWU3TWB2IPANCNFSM47YO4AAA>
> .
>

2021-07-04 15:11 UTC, markwkidd commented
Changed this PR to a draft. I want to ask a few questions, and then hopefully fill in all the remaining todos.

2021-07-04 15:22 UTC, RobLoach commented
While a bunch of these changes are valid, adding a bunch of stub documentation adds bloat without any value. You can change the doxygen settings to adjust more to what Retroarch uses. Like the line break number.

2021-07-04 15:32 UTC, markwkidd commented
For what it's worth, this should all be 80 characters wide already.

I do intend to fill in every stub 😅

On Sun, Jul 4, 2021, 11:22 AM Rob Loach ***@***.***> wrote:

> While a bunch of these changes are valid, adding a bunch of stub
> documentation adds bloat without any value. You can change the doxygen
> settings to adjust more to what Retroarch uses. Like the line break number.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/libretro/RetroArch/pull/12609#issuecomment-873610914>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEVGC5RBIIHIOCQAYB3COP3TWB4CNANCNFSM47YO4AAA>
> .
>

2021-07-06 19:02 UTC, markwkidd commented
I've been able to clarify some of my questions, leading me to identify two sections of this header which I believe are better located in other places.

I have created PRs: https://github.com/libretro/RetroArch/pull/12617 and https://github.com/libretro/RetroArch/pull/12618. 

Meanwhile I hope it makes sense for me to leave this PR as a draft another day or two while I keep filling in the remaining blank spots.

2021-07-12 22:49 UTC, markwkidd commented
Maybe it was predictable, but I am going to narrow the scale of this PR. I have removed the remaining TODO comments -- everything in the PR is actual documentation. I would be grateful for a review and hopefully a merge.

I will continue to work on adding more documentation. Just under a new PR! 🏓

2021-07-15 18:45 UTC, markwkidd commented
@RobLoach do you have any time to look at this PR again? it's cleaned up now with no TODOs. The latter part of the file is split into a separate PR https://github.com/libretro/RetroArch/pull/12661 which also hopefully makes it easier to review

2021-07-17 16:44 UTC, RobLoach requested changes
Looks great! Gives a good understanding of how the API works, and leverages doxygen standards pretty well. Nice work! A few suggestions :wink:

2021-07-17 16:44 UTC, RobLoach commented on input/input_driver.h
> +    * Is this bind valid?
``` suggestion
    * Determines whether or not the binding is valid.
```

2021-07-17 16:44 UTC, RobLoach commented on input/input_driver.h
> +    * @param data  The input state struct
``` suggestion
    * @param data The input state struct.
```

2021-07-17 16:44 UTC, RobLoach commented on input/input_driver.h
> +    * @return       true if the operation is successful.
``` suggestion
    * @return true if the operation is successful.
```

2021-07-17 16:44 UTC, RobLoach commented on input/input_driver.h
> +typedef void (*input_keyboard_line_complete_t)(void *userdata,
``` suggestion
typedef void (*input_keyboard_line_complete_t)(void *userdata,
```

2021-07-17 16:44 UTC, RobLoach commented on input/input_driver.h
> + * @param userdata  ??
``` suggestion
 * @param userdata User data which will be passed to subsequent callbacks.
```

2021-07-17 16:44 UTC, RobLoach commented on input/input_driver.h
> + * @param userdata  ??
``` suggestion
 * @param userdata The user data that was passed through from the keyboard press callback.
```

2021-07-17 16:44 UTC, RobLoach commented on input/input_driver.h
> + * Deprecated: input_config_get_device_name_ptr is required by linuxraw_joypad
``` suggestion
 * Retrieve the device name char pointer.
 *
 * @deprecated input_config_get_device_name_ptr is required by linuxraw_joypad
```

2021-07-17 16:44 UTC, RobLoach commented on input/input_driver.h
> + * Deprecated: input_config_get_device_name_size is required by linuxraw_joypad
``` suggestion
 * Get the size of the device name.
 *
 * @deprecated input_config_get_device_name_size is required by linuxraw_joypad
```

2021-07-17 16:44 UTC, RobLoach commented on input/input_driver.h
> + *
``` suggestion
 *
```

2021-07-17 16:44 UTC, RobLoach commented on input/input_driver.h
> + *
``` suggestion
 *
```

2021-07-17 16:44 UTC, RobLoach commented on input/input_driver.h
> + * @return the device name
``` suggestion
```

2021-07-17 16:44 UTC, RobLoach commented on input/input_driver.h
> + * @return display name for the device
``` suggestion
```

2021-07-17 16:44 UTC, RobLoach commented on input/input_driver.h
> + * @return configuration path for the device
``` suggestion
 * @param path The path of the device config.
```

2021-07-17 16:44 UTC, RobLoach commented on input/input_driver.h
> + * @return configuration name for the device
``` suggestion
 * @param name The name of config to set.
```

2021-07-17 16:44 UTC, RobLoach commented on input/input_driver.h
> + * @return joypad driver
``` suggestion
 * @param driver The driver of which to set the given port to.
```

2021-07-17 16:44 UTC, RobLoach commented on input/input_driver.h
> + * @return vendor ID (vid)
``` suggestion
 * @param vid The vid of which to set the given device port to.
```

2021-07-17 16:44 UTC, RobLoach commented on input/input_driver.h
> + * @return pad ID (pid)
``` suggestion
 * @param pid The pid of which to set the given device port to.
```

2021-07-17 16:44 UTC, RobLoach commented on input/input_driver.h
> + * @return true if the device is autoconfigured
``` suggestion
 * @param autoconfigured Whether or nor the device is configured automatically.
```

2021-07-17 16:44 UTC, RobLoach commented on input/input_driver.h
> + * @return the name index for this device
``` suggestion
 * @param name_index The name index of which to set the device to.
```

2021-07-17 16:44 UTC, RobLoach commented on input/input_driver.h
> + * @param id    device type (eg RETRO_DEVICE_JOYPAD, RETRO_DEVICE_LIGHTGUN)
``` suggestion
 * @param id The device type (RETRO_DEVICE_JOYPAD, RETRO_DEVICE_MOUSE, etc)
```

2021-07-17 17:36 UTC, markwkidd commented
Thank you @RobLoach , it's obvious you looked that this closely. I've accepted your suggestions, and force-pushed the PR to squash the commits.

2021-07-23 04:33 UTC, merged