WIP: (Wayland): support wp_fractional_scale_v1
libretro/RetroArch pull request #15355
Opened 2023-06-05 14:25 UTC by wakira

## Description

Introduce wp_fractional_scale_v1 protocol for proper fractional scaling under wayland.

2023-07-22 17:04 UTC, ColinKinloch commented on gfx/common/wayland_common.c
> +         FRACTIONAL_SCALE_MULT(height, wl->fractional_scale_num) : height * wl->buffer_scale;
```suggestion
      wl->buffer_width  = wl->fractional_scale ?
         FRACTIONAL_SCALE_MULT(width,  wl->fractional_scale_num) : width  * wl->buffer_scale;
      wl->buffer_height = wl->fractional_scale ?
         FRACTIONAL_SCALE_MULT(height, wl->fractional_scale_num) : height * wl->buffer_scale;
```

2023-07-22 17:06 UTC, ColinKinloch requested changes
You should apply the same scaling to `active_touch_positions`.

2023-09-02 12:10 UTC, wakira commented
> You should apply the same scaling to `active_touch_positions`.

fixed

2023-09-02 13:15 UTC, ColinKinloch commented
I just tested it on gnome desktop and it seems to work fine.
Just a nitpick, I feel that the `fractional_scale_num` variables should just be `fractional_scale`.

2023-09-02 13:54 UTC, wakira commented
> Just a nitpick, I feel that the `fractional_scale_num` variables should just be `fractional_scale`.

The reasoning is that while `buffer_scale` is just the integer scale factor (1 for 1x, 2 for 2x ...), the fractional one is different (120 for 1x, 180 for 1.5x ...). I think similar names (`buffer_scale` and `fractional_scale`) might be error-prune.

I'm fine with just `fractional_scale` if that is not a concern.

2023-09-02 13:59 UTC, ColinKinloch commented
> The sent scale is the numerator of a fraction with a denominator of 120.

https://wayland.app/protocols/fractional-scale-v1#wp_fractional_scale_v1:event:preferred_scale

Yeah, it's okay. So long as num is short for numerator. 😄

2023-09-02 14:15 UTC, ColinKinloch approved these changes

2023-11-02 10:55 UTC, ColinKinloch commented
@LibretroAdmin
This works well. It also still seems to rebase without conflicts.

2023-11-15 05:55 UTC, zoltanvb commented
May we have this? :) Although I could not apply the patch version any more to current RA code, so maybe it is again a merge conflict that is not visible here.
https://github.com/wakira/RetroArch/commit/3c9a2f4fc3dbd7d9af96b9ff8dcb56a10bcd446a.patch/

2024-03-05 10:46 UTC, closed without merging