Add support for joining MITM servers over cmdline
libretro/RetroArch pull request #15762
Opened 2023-10-02 18:06 UTC by XK9274

## Description

Adds support for third party server browser users to connect to relay servers when using cmdline as the method to launch RA, currently there seems to be no way to pass the mitm ID on the retroarch commandline - many third party server browsers allow connecting to RA but the connection always fails as the RATS handshake doesn't take place when the mitm session ID isn't passed to `init_netplay(netplay_server, netplay_port, netplay_session)`.

- Have tested on a linux build (OnionUI Miyoo Mini, forked repo here: https://github.com/OnionUI/RetroArch, though it's an older/modified build)
- Have tested on a fresh clone of main RA built through MSYS/MINGW64

## Example connection using `--mitm-session` opt 

<details>

```
Matt@MattPC MINGW64 ~/RAB
$ ./retroarch.exe -C us-east1.relay.retroarch.com --mitm-session kR0ZxtpemrTD7pDd -v -L ./cores/tgbdual_libretro.dll "./rom/Balloon Kid.gb"
[INFO] RetroArch 1.16.0 (Git 14cb3732eb)
[INFO] === Build =======================================
[INFO] CPU Model Name: 11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz
[INFO] Capabilities: MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4 SSE42 AES AVX AVX2
[INFO] Version: 1.16.0
[INFO] Git: 14cb3732eb
[INFO] Built: Oct  2 2023
[INFO] =================================================
[INFO] [Input]: Found input driver: "dinput".
[INFO] [Environ]: SET_SUBSYSTEM_INFO.
[INFO] [Core]: Loading dynamic libretro core from: "./cores/tgbdual_libretro.dll"
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CONTENT_INFO_OVERRIDE.
[INFO] [Content Override]: File Extension: ' gb' - need_fullpath: FALSE, persistent_data: TRUE
[INFO] [Content Override]: File Extension: 'dmg' - need_fullpath: FALSE, persistent_data: TRUE
[INFO] [Content Override]: File Extension: 'gbc' - need_fullpath: FALSE, persistent_data: TRUE
[INFO] [Content Override]: File Extension: 'cgb' - need_fullpath: FALSE, persistent_data: TRUE
[INFO] [Content Override]: File Extension: 'sgb' - need_fullpath: FALSE, persistent_data: TRUE
[INFO] [Overrides]: Redirecting save file to "C:\msys64\home\Matt\RAB\saves\TGB Dual\.netplay\Balloon Kid.srm".
[INFO] [Overrides]: Redirecting save state to "C:\msys64\home\Matt\RAB\states\TGB Dual\Balloon Kid.state".
[INFO] [Environ]: GET_LOG_INTERFACE.
[INFO] [Environ]: PERFORMANCE_LEVEL: 4.
[INFO] [Content]: Loading content file: "./rom/Balloon Kid.gb".
[INFO] [Environ]: SET_VARIABLES.
[ERROR] [Environ]: GET_VARIABLE: tgbdual_screen_placement - Invalid value.
[ERROR] [Environ]: GET_VARIABLE: tgbdual_switch_screens - Invalid value.
[ERROR] [Environ]: GET_VARIABLE: tgbdual_single_screen_mp - Invalid value.
[INFO] [Environ]: SET_GEOMETRY: 320x144, Aspect: 2.222.
[ERROR] [Environ]: GET_VARIABLE: tgbdual_audio_output - Invalid value.
[INFO] [Environ]: SET_INPUT_DESCRIPTORS:
[INFO] [Environ]: SET_PIXEL_FORMAT: RGB565.
[INFO] [Environ]: RETRO_ENVIRONMENT_GET_GAME_INFO_EXT.
[INFO] [Environ]: SET_VARIABLES.
[INFO] [Core]: Saved core options file to "C:\msys64\home\Matt\RAB\config\TGB Dual\TGB Dual.opt".
[INFO] [Environ]: SET_PIXEL_FORMAT: RGB565.
[INFO] [Environ]: SET_GEOMETRY.
[INFO] [Replay]: Found last replay slot: #0
[INFO] [Core]: Version of libretro API: 1, Compiled against API: 1
[INFO] [Core]: Geometry: 320x144, Aspect: 2.222, FPS: 59.73, Sample rate: 44100.00 Hz.
[INFO] [Audio]: Set audio input rate to: 44301.20 Hz.
[INFO] [Video]: Set video size to: 960x432.
[INFO] [Vulkan]: Vulkan dynamic library loaded.
[INFO] [Vulkan]: Found vulkan context: "vk_w".
[INFO] [Vulkan]: Detecting screen resolution: 1920x1080.
[INFO] [Vulkan]: Found GPU at index 0: "NVIDIA GeForce GTX 1660 Ti".
[INFO] [Vulkan]: Using GPU index 0.
[INFO] [Vulkan]: Using fences for WSI acquire.
[INFO] [Vulkan]: Using GPU: "NVIDIA GeForce GTX 1660 Ti".
[INFO] [Vulkan]: Queue family 0 supports 16 sub-queues.
[INFO] [Vulkan]: Got 3 swapchain images.
[INFO] [Vulkan]: Using resolution 960x432.
[INFO] [Vulkan]: Using RGB565 format.
[INFO] [Vulkan]: Loading stock shader.
[INFO] [XInput]: Found XInput v1.4.
[INFO] [Joypad]: Found joypad driver: "dinput".
[INFO] [Video]: Found display server: "win32".
[INFO] [XAudio2]: Requesting 64 ms latency, using 64 ms latency.
[INFO] [Audio]: Started synchronous audio driver.
[INFO] [Microphone]: Initialized microphone driver.
[INFO] [Display]: Found display driver: "vulkan".
[INFO] [Environ]: SET_SUBSYSTEM_INFO.
[INFO] [MIDI]: Output device: "Microsoft GS Wavetable Synth".
[INFO] [Playlist]: Loading history file: "C:\msys64\home\Matt\RAB\content_history.lpl".
[INFO] [Playlist]: Loading history file: "C:\msys64\home\Matt\RAB\content_music_history.lpl".
[INFO] [Playlist]: Loading history file: "C:\msys64\home\Matt\RAB\content_video_history.lpl".
[INFO] [Playlist]: Loading history file: "C:\msys64\home\Matt\RAB\content_image_history.lpl".
[INFO] [Playlist]: Loading favorites file: "C:\msys64\home\Matt\RAB\content_favorites.lpl".
[WARN] [Netplay] WARNING: A netplay peer is running a different version of RetroArch. If problems occur, use the same version.
[WARN] [Netplay] WARNING: A netplay peer is running a different version of the core. If problems occur, use the same version.
[INFO] [Content]: CRC32: 0xd4b655ec.
[INFO] [Netplay] Connected to: "0nion - XK9274"
[INFO] [Netplay] You have joined as player 2 (ping: 490 ms)
[INFO] [Config]: Saved new config to "C:\msys64\home\Matt\RAB\retroarch.cfg".
[INFO] [SRAM]: Saving RAM type #0 to "C:\msys64\home\Matt\RAB\saves\TGB Dual\.netplay\Balloon Kid.srm".
[INFO] [SRAM]: Saved successfully to "C:\msys64\home\Matt\RAB\saves\TGB Dual\.netplay\Balloon Kid.srm".
[INFO] [SRAM]: Saving RAM type #1 to "C:\msys64\home\Matt\RAB\saves\TGB Dual\.netplay\Balloon Kid.rtc".
[INFO] [SRAM]: Saved successfully to "C:\msys64\home\Matt\RAB\saves\TGB Dual\.netplay\Balloon Kid.rtc".
[INFO] [Core]: Content ran for a total of: 00 hours, 00 minutes, 11 seconds.
[INFO] [Runtime]: Saving runtime log file: "C:\msys64\home\Matt\RAB\playlists\logs\TGB Dual\Balloon Kid.lrtl".
[INFO] [Core]: Unloading game..
[INFO] [Core]: Unloading core..
[INFO] [Core]: Unloading core symbols..
[INFO] [Core]: Saved core options file to "C:\msys64\home\Matt\RAB\config\TGB Dual\TGB Dual.opt".
[INFO] [Video]: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.

```

</details>

```./retroarch.exe -C us-east1.relay.retroarch.com --mitm-session kR0ZxtpemrTD7pDd -v -L ./cores/tgbdual_libretro.dll "./rom/Balloon Kid.gb"```

https://github.com/libretro/RetroArch/assets/47260768/8d410eb8-ea04-4cc7-807f-b8bd21a2624f

This PR edits the ```case CMD_EVENT_NETPLAY_INIT:``` block so have also tested to make sure connections (without passing --mitm-session) to a direct IP also continue to work as seen here:

<details>

```
Matt@MattPC MINGW64 ~/RAB
$ ./retroarch.exe -C 81.155.xxx.xxx -v -L ./cores/tgbdual_libretro.dll "./rom/Balloon Kid.gb"
[INFO] RetroArch 1.16.0 (Git 14cb3732eb)
[INFO] === Build =======================================
[INFO] CPU Model Name: 11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz
[INFO] Capabilities: MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4 SSE42 AES AVX AVX2
[INFO] Version: 1.16.0
[INFO] Git: 14cb3732eb
[INFO] Built: Oct  2 2023
[INFO] =================================================
[INFO] [Input]: Found input driver: "dinput".
[INFO] [Environ]: SET_SUBSYSTEM_INFO.
[INFO] [Core]: Loading dynamic libretro core from: "./cores/tgbdual_libretro.dll"
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CONTENT_INFO_OVERRIDE.
[INFO] [Content Override]: File Extension: ' gb' - need_fullpath: FALSE, persistent_data: TRUE
[INFO] [Content Override]: File Extension: 'dmg' - need_fullpath: FALSE, persistent_data: TRUE
[INFO] [Content Override]: File Extension: 'gbc' - need_fullpath: FALSE, persistent_data: TRUE
[INFO] [Content Override]: File Extension: 'cgb' - need_fullpath: FALSE, persistent_data: TRUE
[INFO] [Content Override]: File Extension: 'sgb' - need_fullpath: FALSE, persistent_data: TRUE
[INFO] [Overrides]: Redirecting save file to "C:\msys64\home\Matt\RAB\saves\TG [...]

2023-10-02 20:16 UTC, hizzlekizzle commented
@LibretroAdmin For reference, this is a patch from a downstream fork.

2023-10-03 05:32 UTC, LibretroAdmin requested changes
Do brackets on a new line, and don't use brackets for single line blocks

if that can be addressed I'd be OK with merging this.

2023-10-04 16:50 UTC, XK9274 commented
> Do brackets on a new line, and don't use brackets for single line blocks
> 
> if that can be addressed I'd be OK with merging this.

Fixed :)

2023-10-06 09:02 UTC, merged

2023-10-10 13:39 UTC, LibretroAdmin commented
@XK9274 There were some memory leaks in your PR as a result of that strdup call. 
Check if this feature still works on your end with this commit (since I don't use this feature) -
https://github.com/libretro/RetroArch/commit/58f7051c6188ee7529e1c21ebc4323d5d2ca4851

2023-10-10 15:05 UTC, XK9274 commented
> @XK9274 There were some memory leaks in your PR as a result of that strdup call. 
> Check if this feature still works on your end with this commit (since I don't use this feature) -
> https://github.com/libretro/RetroArch/commit/58f7051c6188ee7529e1c21ebc4323d5d2ca4851

Woops... It wasn't freed 🤦

I'll test this evening when I get off work.

2023-10-10 22:19 UTC, LibretroAdmin commented
Alright, sounds good then.