When loading save file, state, and screenshot directories, attempt to…
libretro/RetroArch pull request #16421
Opened 2024-04-07 19:48 UTC by Nargash

… create them if they do not exist.

## Guidelines

1. Rebase before opening a pull request
2. If you are sending several unrelated fixes or features, use a branch and a separate pull request for each
3. If possible try squashing everything in a single commit. This is particularly beneficial in the case of feature merges since it allows easy bisecting when a problem arises

## Description

In configuration.c, when checking the directory of the save state, save file, or screenshot paths either at initial program load or when applying overrides, we just fall back to a default if the directory is invalid or does not exist. This change makes it so we first attempt to create the directory with path_mkdir first. If that fails then we continue to log a warning and fall back to defaults. From my testing, path_mkdir respects filesystem permissions so we will not create a unwritable directory (it will fail and we go back to the default just like current behavior).

This will make the directory behavior more consistent since currently we do automatically create a Core or Content Directory parent folder when using the options to sort by content directory or core name.

I also updated the warning messages to tell the user where we are falling back to.

## Related Issues

Could not find any

## Related Pull Requests

N/A

## Reviewers

[If possible @mention all the people that should review your pull request]

2024-04-08 23:55 UTC, LibretroAdmin commented
I'm not a fan of implicitly creating directories like this though. I think that should never be forced like this.

2024-04-09 00:41 UTC, Nargash commented
Thank you for the feedback. Would you prefer I back out the mkdir changes and just submit the warning message changes, or is this whole PR not needed at all?

2024-04-27 22:42 UTC, RobLoach commented
Yeah, just the warnings should be good. It's likely the installer that should set up those directories/configurations rather than the application itself.

2024-04-27 22:44 UTC, RobLoach commented on configuration.c
> +               && !path_mkdir(settings->paths.directory_screenshot))
``` suggestion
      else if (!path_is_directory(settings->paths.directory_screenshot))
```

2024-04-27 22:45 UTC, RobLoach commented on configuration.c
> +               || path_mkdir(tmp_str))
``` suggestion
      else if (path_is_directory(tmp_str))
```

2024-04-27 22:46 UTC, RobLoach commented on configuration.c
> +         RARCH_WARN("[Config]: 'savefile_directory' is not a directory, falling back to \"%s\" \n",dir_get_ptr(RARCH_DIR_SAVEFILE));
``` suggestion
         RARCH_WARN("[Config]: 'savefile_directory' is not a directory, falling back to \"%s\"\n", dir_get_ptr(RARCH_DIR_SAVEFILE));
```

2024-04-27 22:46 UTC, RobLoach commented on configuration.c
> +               || path_mkdir(tmp_str))
``` suggestion
      else if (path_is_directory(tmp_str))
```

2024-04-27 22:46 UTC, RobLoach commented on configuration.c
> +         RARCH_WARN("[Config]: 'savestate_directory' is not a directory, falling back to \"%s\" \n",dir_get_ptr(RARCH_DIR_SAVESTATE));
``` suggestion
         RARCH_WARN("[Config]: 'savestate_directory' is not a directory, falling back to \"%s\"\n", dir_get_ptr(RARCH_DIR_SAVESTATE));
```

2024-04-27 22:47 UTC, RobLoach requested changes
Made inline suggestions for just the message updates.

2024-04-29 00:54 UTC, Nargash commented
> Yeah, just the warnings should be good. It's likely the installer that should set up those directories/configurations rather than the application itself.

Thank you! I have committed your changes (I hope, this is the first time I used the Github suggestions feature which is pretty cool). I agree it makes sense for the installer to handle directory creation, but users can change it later in the configs which is why I initially wanted to try to create the path if it does not exist.

2024-08-18 00:10 UTC, closed without merging