Accessibility: Refactor Android is_narrator_running to align with the Retroarch Accessibility API
libretro/RetroArch pull request #16654
Opened 2024-06-04 23:54 UTC by thgcode

## Guidelines

1. Rebase before opening a pull request
2. If you are sending several unrelated fixes or features, use a branch and a separate pull request for each
3. If possible try squashing everything in a single commit. This is particularly beneficial in the case of feature merges since it allows easy bisecting when a problem arises

## Description

As noted in #16638 the Android accessibility is_narrator_running_android code, even though it is  working, is not respecting RetroArch accessibility API contract of returning a boolean if Talkback is speaking or not. Since we do not have control on when Talkback speaks or when it will speak our messages, this code changes the is_narrator_running_android function to always return false. This way all messages will be sent to Talkback and the operating system or Talkback itself will control if it should speak the messages.

## Related Issues

Comment on Pull request #16638 

## Related Pull Requests

None.

## Reviewers

@BarryJRowe

2024-06-05 23:05 UTC, LibretroAdmin commented on frontend/drivers/platform_unix.h
> +bool RAIsTalkbackRunning(void);
Can you make this lower case?

2024-06-05 23:17 UTC, LibretroAdmin requested changes

2024-06-05 23:17 UTC, LibretroAdmin commented on frontend/drivers/platform_unix.c
> +bool RAIsTalkbackRunning(void)
Make this function name lower case

2024-06-06 05:10 UTC, BarryJRowe commented
Looks good to me.

2024-06-08 17:01 UTC, merged