Update alsa.h
libretro/RetroArch pull request #17092
Opened 2024-10-12 20:43 UTC by Laggamer2005

2024-10-12 21:14 UTC, viachaslavic requested changes

2024-10-12 21:14 UTC, viachaslavic commented on audio/common/alsa.h
> +    bool can_pause;
Please follow the [code style](https://docs.libretro.com/development/coding-standards/)

2024-10-12 21:15 UTC, viachaslavic requested changes

2024-10-12 21:15 UTC, viachaslavic commented on audio/common/alsa.h
> +
Now the below code is redundant

2025-01-02 18:27 UTC, RobLoach commented on audio/common/alsa.h
Yup...
``` suggestion
```

2025-01-19 04:32 UTC, RobLoach commented
Closing this from lack of movement.

2025-01-19 04:32 UTC, closed without merging